- name: Add Docker GPG apt Key
  apt_key:
    url: "{{ docker_gpg_key_address }}"
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: "{{ docker_repo_address }}"
    state: present

- name: Update apt and install docker-ce
  apt:
    name: docker-ce
    state: latest
    update_cache: true

- name: Install Docker Module for Python
  pip:
    name: docker